[package]
name = "pestfoamtest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.14.0"
pest = "2.5.5"
pest_derive = "2.5.5"
