[package]
name = "foamparser"
version = "0.2.0"
edition = "2021"
authors = ["Julio Biason <julio.biason@pm.me>"]
description = "A parser for Foamfiles"

[dependencies]
logos = "0.14.0"
thiserror = "1.0.62"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
